pipelines:
  - name: simple_pipeline
    steps:
      - name: simple_step
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step"'
            - export date=$(date)
            - pushd $res_res_ex_0_resourcePath/data
            - ls -l
            - printenv
        configuration:
          inputResources:
            - name: res_ex_0
      